/*
Name: Eduaro Garcia
Course: DAD 334
Date: 3-14-2019
Project: 3-1 Activity
*/

SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE LAST_NAME = 'Matos' OR LAST_NAME = 'Taylor' /* IMIPORTANT TO NOTE THAT NAMES ARE CAP SENSITIVE */
ORDER BY HIRE_DATE;