/*
Name: Eduaro Garcia
Course: DAD 334
Date: 3-14-2019
Project: 3-1 Activity
*/

SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50 /*CAN ALSO BE IN PARENTHESIS (20,50)*/
ORDER BY LAST_NAME;