/*
Name: Eduaro Garcia
Course: DAD 334
Date: 3-14-2019
Project: 3-1 Activity
*/

SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY SALARY, COMMISSION_PCT;