/*
Name: Eduaro Garcia
Course: DAD 334
Date: 3-17-2019
Project: 2-3 Activity
*/

SELECT RPAD(LAST_NAME, 8),
RPAD(' ', SALARY/1000+1, '*') 
EMPLOYEES_AND_THIER_SALARIES
FROM EMPLOYEES
ORDER BY SALARY DESC;