/*
Name: Eduaro Garcia
Course: DAD 334
Date: 3-17-2019
Project: 2-3 Activity
*/

SELECT LAST_NAME, TRUNC((SYSDATE-HIRE_DATE)/7) AS TENURE
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90
ORDER BY TENURE DESC;