/*
Name: Eduaro Garcia
Course: DAD 334
Date: 3-17-2019
Project: 2-3 Activity
*/

SELECT INITCAP(LAST_NAME) "NAME",
LENGTH(LAST_NAME) "LENGTH OF NAME"
FROM EMPLOYEES
WHERE LAST_NAME LIKE '&NAME%'
ORDER BY LAST_NAME;